---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
#
# Please see the documentation for all configuration options:
#   https://bit.ly/4qeBiwL
#
# See this blog post for suggestions for optimizing your config:
#   https://bit.ly/4zaBEZ4
#
# Regenerate with:
#   dependabot-generator run > .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - skyzyx
    commit-message:
      include: scope
      prefix: chore
    cooldown:
      default-days: 7
    groups:
      batch:
        patterns:
          - '*'
    labels:
      - area:dependencies
      - kind:chore
    schedule:
      interval: monthly
